# Generated by Django 5.2.4 on 2025-07-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
