# Generated by Django 5.2.4 on 2025-07-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_alter_product_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('cover', models.ImageField(upload_to='media/cover_image', verbose_name='Обложка')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Кол-во кв метров')),
                ('geo', models.TextField(verbose_name='Гео')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(verbose_name='Описание')),
                ('promo_video', models.FileField(upload_to='', verbose_name='Промо-видео')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категории')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.city', verbose_name='Город')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/additional')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.estate')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
