# Generated by Django 5.2.4 on 2025-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_options_alter_estate_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='promo_video',
            field=models.FileField(blank=True, null=True, upload_to='media/product_promo_video', verbose_name='Промо-видео'),
        ),
    ]
